##server:
##      port:8766
##spring:
##    application:
##              name:truyum-zuul-gateway
#eureka:
#    client:    
#        registerWithEureka:true
#        fetchRegistry:true
#        serviceUrl.defaultZone:http://localhost:8761/eureka
#    instance:
#        hostname:localhost
#zuul:
##    host:
##      connect-timeout-mills:5000000
##      socket-timeout-mills:5000000
##      ignoredServices:'*'
#    routes:
#          truyum-menuitem-service:
#                      path:/menu/**
#                      serviceId:truyum-menuitem-service
#                      stripPrefix:true
#                     # sensitiveHeaders:Cookie,Set-Cookie    
#    